name: Deploy With mdBook Website

on:
  push:
    branches: [ "up" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        # Installing openscad, ffmpeg, and xvfb for the fake monitor
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad ffmpeg xvfb

      - name: Generate 3D Renders
        # xvfb-run wraps the python script, providing the fake display to OpenSCAD
        run: xvfb-run --auto-servernum python ./docs/nxp-book/emb/render_car.py

      - name: Manual mdBook Install
        run: |
          MDBOOK_VERSION=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          curl -L "https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
          sudo mv mdbook /usr/local/bin/

      - name: Run Build Script
        run: |
          chmod +x ./docs/mdbook-build.sh
          ./docs/mdbook-build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should be the folder containing your ENTIRE site 
          # (including your other pages and the mdbook output)
          path: './docs' 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
